DROP DATABASE USERS;

CREATE DATABASE USERS;

USE USERS;

CREATE TABLE USERS (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    EMAIL VARCHAR(255) UNIQUE,
    password VARCHAR (64) NOT NULL,
    TELEFONO VARCHAR (255) UNIQUE
    NOMBRE VARCHAR (255) UNIQUE
);
