DROP DATABASE USERS;

CREATE DATABASE USERS;

USE USERS;

CREATE TABLE EMAIL (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    EMAIL VARCHAR(255)
);

CREATE TABLE TELEFONO (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    TELEFONO VARCHAR(255)
);

CREATE TABLE NOMBRE (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(255)
);