DROP DATABASE USERS;

CREATE DATABASE USERS;

USE USERS;

CREATE TABLE USERS (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    EMAIL VARCHAR(30) UNIQUE,
    PASSWORD VARCHAR (64) NOT NULL,
    PHONE VARCHAR (30) NOT NULL,
    NAME VARCHAR (30) NOT NULL,
    FOREIGN KEY (EMAIL) REFERENCES USERS(id),
    FOREIGN KEY (PHONE) REFERENCES USERS(id),
    FOREIGN KEY (NAME) REFERENCES USERS(id),
);